; ════════════════════════════════════════════════════════════════
; AgroPulse Firmware v3.0 — PlatformIO Configuration
; Plataforma : ESP32-WROOM-32D / ESP32 DevKit v1
; Framework  : Arduino (C++)
; Monitor    : 115200 baud
; ════════════════════════════════════════════════════════════════

[env:esp32doit-devkit-v1]
platform          = espressif32
board             = esp32doit-devkit-v1
framework         = arduino
monitor_speed     = 115200
upload_speed      = 921600
extra_scripts     = post:generate_hex.py

; Librerías de hardware
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    olikraus/U8g2 @ ^2.35.19
    bblanchon/ArduinoJson @ ^6.21.5
    tzapu/WiFiManager @ ^2.0.17
    madhephaestus/ESP32Servo @ ^0.13.0
    mikalhart/TinyGPSPlus @ ^1.0.3

; Flags de compilación
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -std=gnu++17

; Flags de desarrollo (activa prints de depuración)
[env:debug]
extends           = env:esp32doit-devkit-v1
build_flags       = ${env:esp32doit-devkit-v1.build_flags} -DAGROPULSE_DEBUG=1
